name: Acceptance Tests
on: [push, workflow_dispatch]
jobs:
  kind:
    strategy:
      fail-fast: false
      matrix:
        kind-k8s-version: [1.30.8, 1.31.4, 1.32.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup test tools
        uses: ./.github/actions/setup-test-tools
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
        with:
          config: test/kind/config.yaml
          node_image: kindest/node:v${{ matrix.kind-k8s-version }}
          version: v0.22.0
      - run: bats --tap --timing ./test/acceptance
permissions:
  contents: read
